#!/usr/bin/env python3
"""Generate the zalgo marks used by the Minecraft render-subject page.

The marks are not decoration: they encode two facts about each subject so a
reader can sort a long list by eye before reading a single word.

    direction   class   modeled  -> combining marks above the letters
                        shadered -> combining marks below the letters
                        both     -> marks above and below
    density     tier    1 plain asset file      -> light
                        2 runtime-resolved      -> medium
                        3 compiled or code-only -> heavy

Marks are seeded from the subject id, so the same registry always produces the
same file and the diff stays empty unless the registry actually changed.

Usage:  python3 tools/zalgoize.py [--check]
"""

import argparse
import hashlib
import pathlib
import random
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "_data" / "minecraft_subjects.yml"
MARKS = ROOT / "_data" / "zalgo_marks.yml"

# Combining diacriticals, split by where they render relative to the glyph.
ABOVE = "̀́̂̃̄̆̇̈̊̋̌̑̒̓̈́͆͊͐͑͗͛̚"
BELOW = "̧̖̗̘̙̜̝̞̟̠̣̤̥̦̩̭̮̰̱̹̼ͅ"

# marks per character, by tier
DENSITY = {1: 1, 2: 2, 3: 4}

DIRECTION = {
    "modeled": ("above",),
    "shadered": ("below",),
    "both": ("above", "below"),
}


def mark(text, subject_class, tier, seed):
    """Return `text` with combining marks layered on, deterministically."""
    rng = random.Random(seed)
    sides = DIRECTION[subject_class]
    per_char = DENSITY[tier]
    out = []
    for char in text:
        out.append(char)
        if not char.strip():
            continue
        for side in sides:
            pool = ABOVE if side == "above" else BELOW
            for _ in range(per_char):
                out.append(rng.choice(pool))
    return "".join(out)


def sigil(subject_class, tier, seed):
    """A short standalone badge, same encoding, for tables and legends."""
    return mark("█", subject_class, tier, seed + ":sigil")


def build():
    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    marks = {}
    for entry in registry["subjects"]:
        subject_id = entry["id"]
        subject_class = entry["class"]
        tier = int(entry["tier"])
        if subject_class not in DIRECTION:
            raise SystemExit(f"{subject_id}: unknown class {subject_class!r}")
        if tier not in DENSITY:
            raise SystemExit(f"{subject_id}: unknown tier {tier!r}")
        # Seed on the id only. Renaming the display text must not reshuffle
        # marks for every other subject in the file.
        seed = hashlib.sha256(subject_id.encode("utf-8")).hexdigest()
        marks[subject_id] = {
            "name": mark(entry["subject"], subject_class, tier, seed),
            "sigil": sigil(subject_class, tier, seed),
        }

    header = (
        "# GENERATED by tools/zalgoize.py - do not edit by hand.\n"
        "# Source: _data/minecraft_subjects.yml\n"
        "# Marks above = 3d modelled, marks below = shadered, both = both.\n"
        "# Mark density tracks tier 1/2/3 (asset file / runtime / compiled).\n"
        "\n"
    )
    body = yaml.safe_dump(marks, allow_unicode=True, sort_keys=False, width=4096)
    return header + body


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing if the committed marks are stale",
    )
    args = parser.parse_args()

    generated = build()
    if args.check:
        current = MARKS.read_text(encoding="utf-8") if MARKS.exists() else ""
        if current != generated:
            print(f"{MARKS.relative_to(ROOT)} is stale - run python3 tools/zalgoize.py", file=sys.stderr)
            return 1
        print(f"{MARKS.relative_to(ROOT)} is up to date")
        return 0

    MARKS.write_text(generated, encoding="utf-8")
    print(f"wrote {MARKS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
